server:
  port: 8180

domain:
  account:
    name: account
  accountBank:
    name: accountBank

spring:
  application:
    name: awesome-account-service
  datasource:
    url: jdbc:mysql://localhost:3306/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        accountCreated:
          destination: accountExchange
          group: account.accountCreated
          content-type: application/json
        AccountBankOutput:
          destination: accountBankExchange
          content-type: application/json
        AccountOutput:
          destination: accountExchange
          content-type: application/json
      rabbit:
        bindings:
          accountCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: account.AccountCreated.#
          AccountBankOutput:
            producer:
              routing-key-expression: headers['routeTo']
          AccountOutput:
            producer:
              routing-key-expression: headers['routeTo']

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"