server:
  port: 8183

domain:
  payment:
    name: payment

spring:
  application:
    name: awesome-payment-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
      rabbit:
        bindings:

      bindings:

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"