server:
  port: 8183

domain:
  payment:
    name: payment

spring:
  application:
    name: awesome-payment-service
  datasource:
    url: jdbc:mysql://localhost:3309/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
              
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"